name: linauzunhasan
favicon: null
layout_spectrum: 0.98583
typography_spectrum: 0.41107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dad9d5'
    - '#470e12'
    - '#fa4348'
    - '#394860'
    - '#647087'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
