name: linauzunhasan
favicon: null
layout_spectrum: 0.50098
typography_spectrum: 0.16668605478480458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cc9f84'
    - '#a68060'
    - '#623a18'
    - '#885f42'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
