title: Lina Uzunhasan
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8125
  brandStrength: 0.125
  rhythmicContrast: 0.75
  brandColors:
    - '#dad9d5'
    - '#470e12'
    - '#fa4348'
    - '#394860'
    - '#647087'
  lightness: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: linauzunhasan
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.41107
layout_spectrum: 0.005376344
