title: Lina Uzunhasan
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8125
  brandStrength: 0.6415771
  lightness: 0.75
  brandColors:
    - '#060702'
    - '#0D0D05'
    - '#101008'
    - '#040402'
    - '#111308'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: linauzunhasan
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.41107
layout_spectrum: 0.4157706
