name: linauzunhasan
favicon: null
layout_spectrum: 0.4157706
typography_spectrum: 0.41107
title: Lina Uzunhasan
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#85a9c5'
    - '#450407'
    - '#f5f6fa'
    - '#de2c35'
    - '#095872'
  brandStrength: 0.6415771
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
