name: linauzunhasan
favicon: null
layout_spectrum: 0.71685
typography_spectrum: 0.41107
title: Lina Uzunhasan
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cc9f84'
    - '#a68060'
    - '#623a18'
    - '#885f42'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
