name: linauzunhasan
favicon: null
layout_spectrum: 0.92871
typography_spectrum: 0.16668605478480458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfeff'
    - '#20232a'
    - '#cac9c4'
    - '#57636e'
    - '#c91f2a'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
