name: linauzunhasan
favicon: null
layout_spectrum: 0.71685
typography_spectrum: 0.62687
title: Lina Uzunhasan
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c4c4c4'
    - '#ffffff'
    - '#2a2a2a'
    - '#626262'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
